### ISSUE TITLE
login api error

### ISSUE THREAD

**Issue by sudhirbitsgoa** [sampaiodiego/rocket.chat.load.tester#1]
POST /load/login - 6ms
[ '[API] POST error(login): {"status":401,"data":{"status":"error","error":"Unauthorized","message":"Unauthorized"}}' ]
error joining room { status: 401,
  data: 
   { status: 'error',
     error: 'Unauthorized',
     message: 'Unauthorized' } }

**Comment by sampaiodiego** [comment]
this will always happen because the way it works it always to tries to log in first, if it fails, then it will register the user and then log in.

what do you think it should do? maybe have a flag so it will register first?

**Comment by TBG-FR** [comment]
It could be interesting to have a flag and/or some catch (or even just a message saying it's normal, but handling it is better), to avoid thinking it's a real issue :wink:
