### ISSUE TITLE
Not sure if the load testing tool is working?

### ISSUE THREAD

**Issue by olegmitrakhovich** [sampaiodiego/rocket.chat.load.tester#4]
I have a rocket chat instance installed. I also installed this load testing tool on the same instance by doing git clone of the repo and running: 
                                 sudo docker build -t "name:Dockerfile" .

I tried the commands as per repo's README:

spawn as many clients you want/can
curl -X POST http://localhost:3000/load/connect -d 'howMany=10'

log them in
curl -X POST http://localhost:3000/load/login

subscribe to receive room's messages and events
curl -X POST http://localhost:3000/load/subscribe/GENERAL

start sending messages
curl -X POST http://localhost:3000/load/message/send
 stop sending messages
curl -X DELETE http://localhost:3000/load/message/send

each of the commands above gave me some random output. I am also running HTOP to monitor my CPU usage, don't see any change...Is there a step I missed to activate the load testing tool?

**Comment by sampaiodiego** [comment]
It should work still. Just updated README with current instructions.
